# Generated by Django 5.2.8 on 2025-11-21 05:09

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobseekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, verbose_name='О себе')),
                ('desired_position', models.CharField(max_length=200, verbose_name='Желаемая должность')),
                ('desired_salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Зарплата от')),
                ('desired_salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Зарплата до')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Опыт работы, лет')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG')),
                ('is_open_to_work', models.BooleanField(default=True, verbose_name='Ищу работу')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'jobseeker'}, on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_profile', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'Резюме соискателя',
                'verbose_name_plural': 'Резюме соискателей',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('description', models.TextField(blank=True, verbose_name='Обязанности и достижения')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, verbose_name='Работаю сейчас')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='jobseekers.jobseekerprofile')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
                'ordering': ['-is_current', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Учебное заведение')),
                ('faculty', models.CharField(blank=True, max_length=200, verbose_name='Факультет')),
                ('specialty', models.CharField(max_length=200, verbose_name='Специальность')),
                ('degree', models.CharField(choices=[('secondary', 'Среднее'), ('vocational', 'СПО'), ('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('phd', 'Кандидат/доктор наук')], max_length=100, verbose_name='Степень')),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, verbose_name='Учусь сейчас')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='jobseekers.jobseekerprofile')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
                'ordering': ['-end_year', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='JobseekerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Начальный'), (2, 'Средний'), (3, 'Продвинутый'), (4, 'Эксперт')], default=2)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobseekers.jobseekerprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_models.skill')),
            ],
            options={
                'verbose_name': 'Навык соискателя',
                'unique_together': {('profile', 'skill')},
            },
        ),
    ]
